apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
  namespace: vsn7
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: ronaldo7/oktademo-0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090 # The port that the container is running on in the cluster